[package]
name = "telemetry-parser-py"
version = "0.1.8"
authors = ["Adrian <adrian.eddy@gmail.com>"]
edition = "2018"

[lib]
name = "telemetry_parser"
path = "python-module.rs"
crate-type = ["cdylib"]

[dependencies]
telemetry-parser = { path = "../../" }
pyo3 = { version = "0.15", features = ["extension-module"]}
pythonize = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
