[package]
name = "telemetry-parser-py"
version = "0.3.0"
authors = ["Adrian <adrian.eddy@gmail.com>"]
edition = "2021"

[lib]
name = "telemetry_parser"
path = "python-module.rs"
crate-type = ["cdylib"]

[dependencies]
telemetry-parser = { path = "../../" }
pyo3 = { version = "0.21", features = ["extension-module"]}
pythonize = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
