[package]
name = "telemetry-parser-wasm"
version = "0.1.7"
authors = ["Adrian <adrian.eddy@gmail.com>"]
edition = "2018"

[lib]
name = "telemetry_parser"
path = "wasm-module.rs"
crate-type = ["cdylib"]

[dependencies]
telemetry-parser = { path = "../../" }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
