[package]
name = "gyro2bb"
version = "0.3.0"
authors = ["Adrian <adrian.eddy@gmail.com>"]
edition = "2021"

[[bin]]
name = "gyro2bb"
path = "gyro2bb.rs"

[dependencies]
argh = "0.1"
telemetry-parser = { path = "../../" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
