// This file is @generated by prost-build.
#![allow(dead_code)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClipMetaHeader {
    /// * Unit: microseconds. powerup time
    #[prost(fixed64, tag = "1")]
    pub clip_timestamp: u64,
    #[prost(string, tag = "2")]
    pub proto_file_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub proto_product_version: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub proto_library_version: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub product_name: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub product_serial_number: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub product_firmware_version: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub product_firmware_build_time: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub product_firmware_commit_id: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub product_hardware_version: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamMetaHeader {
    #[prost(uint32, tag = "1")]
    pub stream_id: u32,
    #[prost(enumeration = "stream_meta_header::StreamType", tag = "2")]
    pub stream_type: i32,
}
/// Nested message and enum types in `StreamMetaHeader`.
pub mod stream_meta_header {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum StreamType {
        Video = 0,
        Audio = 1,
    }
    impl StreamType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Video => "STREAM_TYPE_VIDEO",
                Self::Audio => "STREAM_TYPE_AUDIO",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "STREAM_TYPE_VIDEO" => Some(Self::Video),
                "STREAM_TYPE_AUDIO" => Some(Self::Audio),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FrameMetaHeader {
    /// * Unit: microseconds. from powerup time
    #[prost(fixed64, tag = "1")]
    pub frame_timestamp: u64,
    /// * Frame sequence number. start from 0
    #[prost(fixed64, tag = "2")]
    pub frame_seq: u64,
    /// * Which stream this frame belongs to
    #[prost(uint32, tag = "3")]
    pub stream_id: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceMetaHeader {
    /// * Device ID
    #[prost(uint32, tag = "1")]
    pub device_id: u32,
    #[prost(enumeration = "device_meta_header::DeviceType", tag = "2")]
    pub device_type: i32,
}
/// Nested message and enum types in `DeviceMetaHeader`.
pub mod device_meta_header {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum DeviceType {
        Undefined = 0,
        Camera = 1,
    }
    impl DeviceType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Undefined => "DEVICE_TYPE_UNDEFINED",
                Self::Camera => "DEVICE_TYPE_CAMERA",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "DEVICE_TYPE_UNDEFINED" => Some(Self::Undefined),
                "DEVICE_TYPE_CAMERA" => Some(Self::Camera),
                _ => None,
            }
        }
    }
}
/// Multi Camera
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MultiCameraLinkSync {
    #[prost(enumeration = "multi_camera_link_sync::MultiCameraLinkMode", tag = "1")]
    pub multi_camera_link_mode: i32,
    #[prost(enumeration = "multi_camera_link_sync::MultiCameraLinkRole", tag = "2")]
    pub multi_camera_link_role: i32,
    #[prost(enumeration = "multi_camera_link_sync::MultiCameraLinkTrigger", tag = "3")]
    pub multi_camera_link_trigger: i32,
}
/// Nested message and enum types in `MultiCameraLinkSync`.
pub mod multi_camera_link_sync {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MultiCameraLinkMode {
        None = 0,
        Pixellink = 1,
        Ezlink = 2,
        Genlock = 3,
    }
    impl MultiCameraLinkMode {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::None => "MULTI_CAMERA_LINK_MODE_NONE",
                Self::Pixellink => "MULTI_CAMERA_LINK_MODE_PIXELLINK",
                Self::Ezlink => "MULTI_CAMERA_LINK_MODE_EZLINK",
                Self::Genlock => "MULTI_CAMERA_LINK_MODE_GENLOCK",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "MULTI_CAMERA_LINK_MODE_NONE" => Some(Self::None),
                "MULTI_CAMERA_LINK_MODE_PIXELLINK" => Some(Self::Pixellink),
                "MULTI_CAMERA_LINK_MODE_EZLINK" => Some(Self::Ezlink),
                "MULTI_CAMERA_LINK_MODE_GENLOCK" => Some(Self::Genlock),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MultiCameraLinkRole {
        I = 0,
        M = 1,
        S = 2,
    }
    impl MultiCameraLinkRole {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::I => "MULTI_CAMERA_LINK_ROLE_I",
                Self::M => "MULTI_CAMERA_LINK_ROLE_M",
                Self::S => "MULTI_CAMERA_LINK_ROLE_S",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "MULTI_CAMERA_LINK_ROLE_I" => Some(Self::I),
                "MULTI_CAMERA_LINK_ROLE_M" => Some(Self::M),
                "MULTI_CAMERA_LINK_ROLE_S" => Some(Self::S),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MultiCameraLinkTrigger {
        Auto = 0,
        Manual = 1,
    }
    impl MultiCameraLinkTrigger {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Auto => "MULTI_CAMERA_LINK_TRIGGER_AUTO",
                Self::Manual => "MULTI_CAMERA_LINK_TRIGGER_MANUAL",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "MULTI_CAMERA_LINK_TRIGGER_AUTO" => Some(Self::Auto),
                "MULTI_CAMERA_LINK_TRIGGER_MANUAL" => Some(Self::Manual),
                _ => None,
            }
        }
    }
}
/// Lens
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LensInfo {
    #[prost(string, tag = "1")]
    pub lens_name: ::prost::alloc::string::String,
    /// * Unit: mm
    #[prost(float, tag = "2")]
    pub image_circle_diameter: f32,
}
/// ImageSensor
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ImageSensorInfo {
    /// * Unit: nm
    #[prost(uint32, tag = "1")]
    pub pixel_size_nm: u32,
    /// * Unit: pixels
    #[prost(uint32, tag = "2")]
    pub sensor_pixel_width: u32,
    /// * Unit: pixels
    #[prost(uint32, tag = "3")]
    pub sensor_pixel_height: u32,
    /// * Unit: fps
    #[prost(float, tag = "4")]
    pub frame_rate: f32,
    /// * Unit: microseconds
    #[prost(float, tag = "5")]
    pub read_out_time: f32,
    #[prost(enumeration = "image_sensor_info::ReadOutDirection", tag = "6")]
    pub read_out_direction: i32,
    /// * Unit: pixels
    #[prost(uint32, optional, tag = "7")]
    pub crop_x: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "8")]
    pub crop_y: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "9")]
    pub crop_width: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "10")]
    pub crop_height: ::core::option::Option<u32>,
}
/// Nested message and enum types in `ImageSensorInfo`.
pub mod image_sensor_info {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum ReadOutDirection {
        TopToBottom = 0,
        BottomToTop = 1,
        RightToLeft = 2,
        LeftToRight = 3,
    }
    impl ReadOutDirection {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::TopToBottom => "READ_OUT_DIRECTION_TOP_TO_BOTTOM",
                Self::BottomToTop => "READ_OUT_DIRECTION_BOTTOM_TO_TOP",
                Self::RightToLeft => "READ_OUT_DIRECTION_RIGHT_TO_LEFT",
                Self::LeftToRight => "READ_OUT_DIRECTION_LEFT_TO_RIGHT",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "READ_OUT_DIRECTION_TOP_TO_BOTTOM" => Some(Self::TopToBottom),
                "READ_OUT_DIRECTION_BOTTOM_TO_TOP" => Some(Self::BottomToTop),
                "READ_OUT_DIRECTION_RIGHT_TO_LEFT" => Some(Self::RightToLeft),
                "READ_OUT_DIRECTION_LEFT_TO_RIGHT" => Some(Self::LeftToRight),
                _ => None,
            }
        }
    }
}
/// Storage
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorageInfo {
    #[prost(enumeration = "storage_info::StorageType", tag = "1")]
    pub storage_type: i32,
    /// * Unit: bytes
    #[prost(uint64, tag = "2")]
    pub free_space_size: u64,
    /// * Unit: bytes
    #[prost(uint64, tag = "3")]
    pub total_space_size: u64,
    #[prost(string, tag = "4")]
    pub storage_name: ::prost::alloc::string::String,
}
/// Nested message and enum types in `StorageInfo`.
pub mod storage_info {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum StorageType {
        Undefined = 0,
        Sd = 1,
        Cfe = 2,
        Usb = 3,
        Cfast = 4,
    }
    impl StorageType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Undefined => "STORAGE_TYPE_UNDEFINED",
                Self::Sd => "STORAGE_TYPE_SD",
                Self::Cfe => "STORAGE_TYPE_CFE",
                Self::Usb => "STORAGE_TYPE_USB",
                Self::Cfast => "STORAGE_TYPE_CFAST",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "STORAGE_TYPE_UNDEFINED" => Some(Self::Undefined),
                "STORAGE_TYPE_SD" => Some(Self::Sd),
                "STORAGE_TYPE_CFE" => Some(Self::Cfe),
                "STORAGE_TYPE_USB" => Some(Self::Usb),
                "STORAGE_TYPE_CFAST" => Some(Self::Cfast),
                _ => None,
            }
        }
    }
}
/// VideoStream
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct VideoStreamMeta {
    /// * Unit: pixels
    #[prost(uint32, tag = "1")]
    pub width: u32,
    /// * Unit: pixels
    #[prost(uint32, tag = "2")]
    pub height: u32,
    #[prost(float, tag = "3")]
    pub project_fps: f32,
    #[prost(float, tag = "4")]
    pub shot_fps: f32,
    /// * Unit: degree, e.g. 180 for upside down
    #[prost(uint32, tag = "6")]
    pub rotation: u32,
    /// * Unit: seconds
    #[prost(uint32, tag = "7")]
    pub timelapse_interval: u32,
    /// * Unit: seconds
    #[prost(uint32, tag = "8")]
    pub split_duration: u32,
    /// * Unit: seconds
    #[prost(uint32, tag = "9")]
    pub preroll_duration: u32,
    #[prost(enumeration = "video_stream_meta::VideoCodec", tag = "10")]
    pub video_codec: i32,
}
/// Nested message and enum types in `VideoStreamMeta`.
pub mod video_stream_meta {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum VideoCodec {
        H264 = 0,
        H265 = 1,
        Jpeg = 2,
        Prores = 3,
        Proresraw = 4,
    }
    impl VideoCodec {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::H264 => "VIDEO_CODEC_H264",
                Self::H265 => "VIDEO_CODEC_H265",
                Self::Jpeg => "VIDEO_CODEC_JPEG",
                Self::Prores => "VIDEO_CODEC_PRORES",
                Self::Proresraw => "VIDEO_CODEC_PRORESRAW",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "VIDEO_CODEC_H264" => Some(Self::H264),
                "VIDEO_CODEC_H265" => Some(Self::H265),
                "VIDEO_CODEC_JPEG" => Some(Self::Jpeg),
                "VIDEO_CODEC_PRORES" => Some(Self::Prores),
                "VIDEO_CODEC_PRORESRAW" => Some(Self::Proresraw),
                _ => None,
            }
        }
    }
}
/// Focal Length
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FocalLength {
    /// * Unit: mm
    #[prost(float, tag = "1")]
    pub focal_length: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DigitalZoonRation {
    #[prost(float, tag = "1")]
    pub digital_zoon_ratio: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FocusDistance {
    #[prost(enumeration = "focus_distance::FocusDistanceUnit", tag = "1")]
    pub focus_distance_unit: i32,
    /// * Unit: mm or inch
    #[prost(float, tag = "2")]
    pub focus_distance: f32,
    /// * internal use only
    #[prost(fixed32, tag = "3")]
    pub focus_position: u32,
}
/// Nested message and enum types in `FocusDistance`.
pub mod focus_distance {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum FocusDistanceUnit {
        Mm = 0,
        In = 1,
    }
    impl FocusDistanceUnit {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Mm => "FOCUS_DISTANCE_UNIT_MM",
                Self::In => "FOCUS_DISTANCE_UNIT_IN",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "FOCUS_DISTANCE_UNIT_MM" => Some(Self::Mm),
                "FOCUS_DISTANCE_UNIT_IN" => Some(Self::In),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FocusData {
    #[prost(enumeration = "focus_data::FocusMode", tag = "1")]
    pub focus_mode: i32,
    #[prost(bool, tag = "2")]
    pub follow_ptz: bool,
    #[prost(message, optional, tag = "3")]
    pub focus_distance: ::core::option::Option<FocusDistance>,
    #[prost(message, optional, tag = "4")]
    pub focus_roi: ::core::option::Option<Rect>,
    #[prost(enumeration = "focus_data::AutoFocusSensitivity", tag = "5")]
    pub auto_focus_sensitivity: i32,
    #[prost(enumeration = "focus_data::AutoFocusSpeed", tag = "6")]
    pub auto_focus_speed: i32,
    #[prost(message, optional, tag = "7")]
    pub limit_near: ::core::option::Option<FocusDistance>,
    #[prost(message, optional, tag = "8")]
    pub limit_far: ::core::option::Option<FocusDistance>,
}
/// Nested message and enum types in `FocusData`.
pub mod focus_data {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum FocusMode {
        Auto = 0,
        Manual = 1,
    }
    impl FocusMode {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Auto => "FOCUS_MODE_AUTO",
                Self::Manual => "FOCUS_MODE_MANUAL",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "FOCUS_MODE_AUTO" => Some(Self::Auto),
                "FOCUS_MODE_MANUAL" => Some(Self::Manual),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum AutoFocusSensitivity {
        Low = 0,
        Medium = 1,
        High = 2,
    }
    impl AutoFocusSensitivity {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Low => "AUTO_FOCUS_SENSITIVITY_LOW",
                Self::Medium => "AUTO_FOCUS_SENSITIVITY_MEDIUM",
                Self::High => "AUTO_FOCUS_SENSITIVITY_HIGH",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "AUTO_FOCUS_SENSITIVITY_LOW" => Some(Self::Low),
                "AUTO_FOCUS_SENSITIVITY_MEDIUM" => Some(Self::Medium),
                "AUTO_FOCUS_SENSITIVITY_HIGH" => Some(Self::High),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum AutoFocusSpeed {
        Slow = 0,
        Medium = 1,
        Fast = 2,
    }
    impl AutoFocusSpeed {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Slow => "AUTO_FOCUS_SPEED_SLOW",
                Self::Medium => "AUTO_FOCUS_SPEED_MEDIUM",
                Self::Fast => "AUTO_FOCUS_SPEED_FAST",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "AUTO_FOCUS_SPEED_SLOW" => Some(Self::Slow),
                "AUTO_FOCUS_SPEED_MEDIUM" => Some(Self::Medium),
                "AUTO_FOCUS_SPEED_FAST" => Some(Self::Fast),
                _ => None,
            }
        }
    }
}
/// white balance
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WhiteBalanceData {
    #[prost(enumeration = "white_balance_data::WhiteBalanceMode", tag = "1")]
    pub white_balance_mode: i32,
    #[prost(enumeration = "white_balance_data::AutoWhiteBalancPriority", tag = "2")]
    pub auto_white_balance_priority: i32,
    #[prost(fixed32, tag = "3")]
    pub kelvin: u32,
    #[prost(fixed32, tag = "4")]
    pub tint: u32,
    /// * 3 channel gain
    #[prost(fixed32, repeated, tag = "5")]
    pub rgb_gain: ::prost::alloc::vec::Vec<u32>,
    /// * 3 channel gain offset
    #[prost(fixed32, repeated, tag = "6")]
    pub rgb_offset: ::prost::alloc::vec::Vec<u32>,
}
/// Nested message and enum types in `WhiteBalanceData`.
pub mod white_balance_data {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum WhiteBalanceMode {
        Auto = 0,
        /// todo
        Manual = 1,
    }
    impl WhiteBalanceMode {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Auto => "WHITE_BALANCE_MODE_AUTO",
                Self::Manual => "WHITE_BALANCE_MODE_MANUAL",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "WHITE_BALANCE_MODE_AUTO" => Some(Self::Auto),
                "WHITE_BALANCE_MODE_MANUAL" => Some(Self::Manual),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum AutoWhiteBalancPriority {
        AutoWhiteBalancePriorityAmbient = 0,
        AutoWhiteBalancePriorityWhite = 1,
    }
    impl AutoWhiteBalancPriority {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::AutoWhiteBalancePriorityAmbient => {
                    "AUTO_WHITE_BALANCE_PRIORITY_AMBIENT"
                }
                Self::AutoWhiteBalancePriorityWhite => {
                    "AUTO_WHITE_BALANCE_PRIORITY_WHITE"
                }
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "AUTO_WHITE_BALANCE_PRIORITY_AMBIENT" => {
                    Some(Self::AutoWhiteBalancePriorityAmbient)
                }
                "AUTO_WHITE_BALANCE_PRIORITY_WHITE" => {
                    Some(Self::AutoWhiteBalancePriorityWhite)
                }
                _ => None,
            }
        }
    }
}
/// exposure
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ExposureData {
    #[prost(float, tag = "1")]
    pub iso: f32,
    /// *Unit: seconds
    #[prost(float, tag = "2")]
    pub exposure_time: f32,
    #[prost(float, tag = "3")]
    pub f_no: f32,
    #[prost(float, tag = "4")]
    pub ev: f32,
    /// *Unit: degree
    #[prost(float, optional, tag = "5")]
    pub shutter_angle: ::core::option::Option<f32>,
    /// * e.g. 1 for 1/100
    #[prost(fixed32, optional, tag = "6")]
    pub shutter_speed_num: ::core::option::Option<u32>,
    /// * e.g. 100 for 1/100
    #[prost(fixed32, optional, tag = "7")]
    pub shutter_speed_den: ::core::option::Option<u32>,
    #[prost(enumeration = "exposure_data::ShutterUnit", tag = "8")]
    pub shutter_unit: i32,
    #[prost(enumeration = "exposure_data::ExposureControlMode", tag = "9")]
    pub exposure_shutter_mode: i32,
    #[prost(enumeration = "exposure_data::ExposureControlMode", tag = "10")]
    pub exposure_iso_mode: i32,
    #[prost(enumeration = "exposure_data::ExposureControlMode", tag = "11")]
    pub exposure_f_no_mode: i32,
}
/// Nested message and enum types in `ExposureData`.
pub mod exposure_data {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum ShutterUnit {
        Time = 0,
        Angle = 1,
    }
    impl ShutterUnit {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Time => "SHUTTER_UNIT_TIME",
                Self::Angle => "SHUTTER_UNIT_ANGLE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "SHUTTER_UNIT_TIME" => Some(Self::Time),
                "SHUTTER_UNIT_ANGLE" => Some(Self::Angle),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum ExposureControlMode {
        Auto = 0,
        Manual = 1,
    }
    impl ExposureControlMode {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Auto => "EXPOSURE_CONTROL_MODE_AUTO",
                Self::Manual => "EXPOSURE_CONTROL_MODE_MANUAL",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "EXPOSURE_CONTROL_MODE_AUTO" => Some(Self::Auto),
                "EXPOSURE_CONTROL_MODE_MANUAL" => Some(Self::Manual),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExposureIndex {
    #[prost(fixed32, tag = "1")]
    pub exposure_index: u32,
}
/// Image
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ImageProfile {
    #[prost(string, tag = "1")]
    pub profile_name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ImageDenoise {
    #[prost(float, tag = "1")]
    pub denoising_strength: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ImageSharpen {
    #[prost(float, tag = "1")]
    pub sharpening_strength: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ImageHueSat {
    #[prost(float, tag = "1")]
    pub brightness: f32,
    #[prost(float, tag = "2")]
    pub contrast: f32,
    #[prost(float, tag = "3")]
    pub saturation: f32,
    #[prost(float, tag = "4")]
    pub hue: f32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ImageAdvancedColorMatrix {
    /// * On/Off
    #[prost(bool, tag = "1")]
    pub user_color_matrix_status: bool,
    #[prost(fixed32, repeated, tag = "2")]
    pub matrix: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ImageAdvancedColorHueSat {
    /// * On/Off
    #[prost(bool, tag = "1")]
    pub user_color_hue_sat_status: bool,
    #[prost(fixed32, tag = "2")]
    pub channel_count: u32,
    #[prost(fixed32, repeated, tag = "3")]
    pub hue: ::prost::alloc::vec::Vec<u32>,
    #[prost(fixed32, repeated, tag = "4")]
    pub saturation: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ImageBlackLevel {
    /// * On/Off
    #[prost(bool, tag = "1")]
    pub image_black_level_status: bool,
    #[prost(fixed32, repeated, tag = "2")]
    pub black_level: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Rect {
    #[prost(float, tag = "1")]
    pub x: f32,
    #[prost(float, tag = "2")]
    pub y: f32,
    #[prost(float, tag = "3")]
    pub width: f32,
    #[prost(float, tag = "4")]
    pub height: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Point {
    #[prost(float, tag = "1")]
    pub x: f32,
    #[prost(float, tag = "2")]
    pub y: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Size {
    #[prost(float, tag = "1")]
    pub width: f32,
    #[prost(float, tag = "2")]
    pub height: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Quaternion {
    #[prost(float, tag = "1")]
    pub qw: f32,
    #[prost(float, tag = "2")]
    pub qx: f32,
    #[prost(float, tag = "3")]
    pub qy: f32,
    #[prost(float, tag = "4")]
    pub qz: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct EulerAngles {
    /// * Unit: rad
    #[prost(float, tag = "1")]
    pub roll: f32,
    /// * Unit: rad
    #[prost(float, tag = "2")]
    pub pitch: f32,
    /// * Unit: rad
    #[prost(float, tag = "3")]
    pub yaw: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DegreeAngles {
    /// * Unit: degree
    #[prost(float, tag = "1")]
    pub roll: f32,
    /// * Unit: degree
    #[prost(float, tag = "2")]
    pub pitch: f32,
    /// * Unit: degree
    #[prost(float, tag = "3")]
    pub yaw: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Acceleration {
    /// * Unit: m/s^2
    #[prost(float, tag = "1")]
    pub ax: f32,
    /// * Unit: m/s^2
    #[prost(float, tag = "2")]
    pub ay: f32,
    /// * Unit: m/s^2
    #[prost(float, tag = "3")]
    pub az: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AngularVelocity {
    /// * Unit: rad/s
    #[prost(float, tag = "1")]
    pub wx: f32,
    /// * Unit: rad/s
    #[prost(float, tag = "2")]
    pub wy: f32,
    /// * Unit: rad/s
    #[prost(float, tag = "3")]
    pub wz: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Velocity {
    /// * Unit: m/s
    #[prost(float, tag = "1")]
    pub vx: f32,
    /// * Unit: m/s
    #[prost(float, tag = "2")]
    pub vy: f32,
    /// * Unit: m/s
    #[prost(float, tag = "3")]
    pub vz: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Position {
    /// * Unit: m
    #[prost(float, tag = "1")]
    pub px: f32,
    /// * Unit: m
    #[prost(float, tag = "2")]
    pub py: f32,
    /// * Unit: m
    #[prost(float, tag = "3")]
    pub pz: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImuInfo {
    /// * Unit: Hz
    #[prost(float, tag = "1")]
    pub sampling_rate: f32,
    /// * Unit: deg/s/LSB
    #[prost(float, tag = "2")]
    pub gyro_scale: f32,
    /// * Unit: m/s^2/LSB
    #[prost(float, tag = "3")]
    pub accel_scale: f32,
    /// * Unit: uT/LSB
    #[prost(float, tag = "4")]
    pub mag_scale: f32,
    /// * Unit: us
    #[prost(float, tag = "5")]
    pub time_offset: f32,
    /// * 3x3 matrix
    #[prost(float, repeated, tag = "6")]
    pub orientation_matrix: ::prost::alloc::vec::Vec<f32>,
}
/// * RAW_IMU = \[gx, gy, gz, ax, ay, az\]
/// IMU_DATA = \[gx * gyro_scale, gy * gyro_scale, gz * gyro_scale, ax * accel_scale, ay * accel_scale, az * accel_scale\]
/// IMU_DATA = RAW_IMU * \[orientation_matrix\]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ImuRawItem {
    /// * Unit: LSB
    #[prost(float, tag = "1")]
    pub gx: f32,
    /// * Unit: LSB
    #[prost(float, tag = "2")]
    pub gy: f32,
    /// * Unit: LSB
    #[prost(float, tag = "3")]
    pub gz: f32,
    /// * Unit: LSB
    #[prost(float, tag = "4")]
    pub ax: f32,
    /// * Unit: LSB
    #[prost(float, tag = "5")]
    pub ay: f32,
    /// * Unit: LSB
    #[prost(float, tag = "6")]
    pub az: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImuData {
    /// * Unit: microseconds
    #[prost(fixed64, tag = "1")]
    pub timestamp: u64,
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<ImuRawItem>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceAttitude {
    /// * Unit: microseconds. from powerup time
    #[prost(uint32, tag = "1")]
    pub timestamp: u32,
    /// * Unit: quaternion
    #[prost(message, repeated, tag = "2")]
    pub attitude: ::prost::alloc::vec::Vec<Quaternion>,
}
/// Pan Tilt
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PanTiltData {
    /// * Unit: degree
    #[prost(float, tag = "1")]
    pub pan: f32,
    /// * Unit: degree
    #[prost(float, tag = "2")]
    pub tilt: f32,
    /// * Unit: degree
    #[prost(float, tag = "3")]
    pub roll: f32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AiBoundingBox {
    #[prost(fixed32, tag = "1")]
    pub class_id: u32,
    #[prost(enumeration = "AiTrackingState", tag = "2")]
    pub tracking_state: i32,
    #[prost(string, tag = "3")]
    pub class_name: ::prost::alloc::string::String,
    #[prost(fixed32, tag = "4")]
    pub score: u32,
    #[prost(fixed32, tag = "5")]
    pub x: u32,
    #[prost(fixed32, tag = "6")]
    pub y: u32,
    #[prost(fixed32, tag = "7")]
    pub width: u32,
    #[prost(fixed32, tag = "8")]
    pub height: u32,
    /// * Unit: mm
    #[prost(fixed32, tag = "9")]
    pub distance: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AimotData {
    /// tood: other settings
    #[prost(fixed32, tag = "1")]
    pub mot_count: u32,
    #[prost(message, repeated, tag = "2")]
    pub bounding_boxes: ::prost::alloc::vec::Vec<AiBoundingBox>,
}
/// system
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SystemInfo {
    /// * Unit: C
    #[prost(float, tag = "1")]
    pub temperature: f32,
    /// * Unit: V
    #[prost(float, tag = "2")]
    pub voltage: f32,
    #[prost(enumeration = "system_info::PowerSource", tag = "3")]
    pub power_source: i32,
}
/// Nested message and enum types in `SystemInfo`.
pub mod system_info {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum PowerSource {
        Undefined = 0,
        Battery = 1,
        Dc = 2,
        Poe = 3,
    }
    impl PowerSource {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Undefined => "POWER_SOURCE_UNDEFINED",
                Self::Battery => "POWER_SOURCE_BATTERY",
                Self::Dc => "POWER_SOURCE_DC",
                Self::Poe => "POWER_SOURCE_POE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "POWER_SOURCE_UNDEFINED" => Some(Self::Undefined),
                "POWER_SOURCE_BATTERY" => Some(Self::Battery),
                "POWER_SOURCE_DC" => Some(Self::Dc),
                "POWER_SOURCE_POE" => Some(Self::Poe),
                _ => None,
            }
        }
    }
}
/// AI
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AiTrackingState {
    AitrackingStateUntracked = 0,
    AitrackingStateTracked = 1,
}
impl AiTrackingState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::AitrackingStateUntracked => "AITRACKING_STATE_UNTRACKED",
            Self::AitrackingStateTracked => "AITRACKING_STATE_TRACKED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AITRACKING_STATE_UNTRACKED" => Some(Self::AitrackingStateUntracked),
            "AITRACKING_STATE_TRACKED" => Some(Self::AitrackingStateTracked),
            _ => None,
        }
    }
}
/// *
/// Product metadata
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProductMeta {
    #[prost(message, optional, tag = "1")]
    pub clip_meta: ::core::option::Option<ClipMeta>,
    #[prost(message, optional, tag = "2")]
    pub stream_meta: ::core::option::Option<StreamMeta>,
    #[prost(message, optional, tag = "3")]
    pub frame_meta: ::core::option::Option<FrameMeta>,
}
/// *
/// Per clip metadata
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClipMeta {
    #[prost(message, optional, tag = "1")]
    pub clip_meta_header: ::core::option::Option<ClipMetaHeader>,
    #[prost(message, optional, tag = "2")]
    pub lens_info: ::core::option::Option<LensInfo>,
    #[prost(message, optional, tag = "3")]
    pub image_sensor_info: ::core::option::Option<ImageSensorInfo>,
    #[prost(message, optional, tag = "4")]
    pub storage_info: ::core::option::Option<StorageInfo>,
    #[prost(message, optional, tag = "5")]
    pub imu_info: ::core::option::Option<ImuInfo>,
    #[prost(message, optional, tag = "6")]
    pub multi_camera_link_sync: ::core::option::Option<MultiCameraLinkSync>,
}
/// *
/// Per stream metadata
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamMeta {
    #[prost(message, optional, tag = "1")]
    pub stream_meta_header: ::core::option::Option<StreamMetaHeader>,
    #[prost(message, optional, tag = "2")]
    pub video_stream_meta: ::core::option::Option<VideoStreamMeta>,
    #[prost(message, optional, tag = "3")]
    pub image_profile: ::core::option::Option<ImageProfile>,
    #[prost(message, optional, tag = "4")]
    pub image_denoise: ::core::option::Option<ImageDenoise>,
    #[prost(message, optional, tag = "5")]
    pub image_sharpen: ::core::option::Option<ImageSharpen>,
    #[prost(message, optional, tag = "6")]
    pub image_hue_sat: ::core::option::Option<ImageHueSat>,
    #[prost(message, optional, tag = "7")]
    pub image_advanced_color_matrix: ::core::option::Option<ImageAdvancedColorMatrix>,
    #[prost(message, optional, tag = "8")]
    pub image_advanced_color_hue_sat: ::core::option::Option<ImageAdvancedColorHueSat>,
    #[prost(message, optional, tag = "9")]
    pub image_black_level: ::core::option::Option<ImageBlackLevel>,
}
/// *
/// Per frame metadata
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FrameMeta {
    #[prost(message, optional, tag = "1")]
    pub frame_meta_header: ::core::option::Option<FrameMetaHeader>,
    #[prost(message, optional, tag = "2")]
    pub frame_meta_of_camera: ::core::option::Option<FrameMetaOfCamera>,
    #[prost(message, optional, tag = "3")]
    pub frame_meta_of_imu: ::core::option::Option<FrameMetaOfImu>,
    #[prost(message, optional, tag = "4")]
    pub frame_meta_of_pan_tilt: ::core::option::Option<FrameMetaOfPanTilt>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FrameMetaOfCamera {
    #[prost(message, optional, tag = "1")]
    pub device_meta_header: ::core::option::Option<DeviceMetaHeader>,
    #[prost(message, optional, tag = "2")]
    pub exposure_data: ::core::option::Option<ExposureData>,
    #[prost(message, optional, tag = "3")]
    pub white_balance_data: ::core::option::Option<WhiteBalanceData>,
    #[prost(message, optional, tag = "4")]
    pub focus_data: ::core::option::Option<FocusData>,
    #[prost(message, optional, tag = "5")]
    pub focal_length: ::core::option::Option<FocalLength>,
    #[prost(message, optional, tag = "6")]
    pub digital_zoon_ration: ::core::option::Option<DigitalZoonRation>,
    #[prost(message, optional, tag = "7")]
    pub system_info: ::core::option::Option<SystemInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FrameMetaOfImu {
    #[prost(message, optional, tag = "1")]
    pub imu_data: ::core::option::Option<ImuData>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FrameMetaOfPanTilt {
    #[prost(message, optional, tag = "1")]
    pub pan_tilt_data: ::core::option::Option<PanTiltData>,
}
